# Lession 14 - Minibatches and Epochs

In [35]:
import numpy as np
np.random.seed(0)

In [36]:
BATCH_SIZE = 6
EPOCHS = 2
N = 40

Generate data

In [5]:
data = np.arange(N)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Randomize the data

In [32]:
rand_data = np.random.permutation(data)
rand_data

array([25,  7, 24, 19, 36, 28, 13,  5, 29, 32, 12, 39, 37, 15, 31,  6,  0,
       16, 38, 21,  8, 11, 22, 10,  4,  1, 26,  9, 14, 27, 33, 17, 20, 18,
        3, 30, 35, 34,  2, 23])

Copy data from beginning to end so each set has same amount of data.

In [33]:
rand_data = np.append(rand_data, rand_data[range(int(np.ceil(N/BATCH_SIZE)*BATCH_SIZE-N))])
rand_data

array([25,  7, 24, 19, 36, 28, 13,  5, 29, 32, 12, 39, 37, 15, 31,  6,  0,
       16, 38, 21,  8, 11, 22, 10,  4,  1, 26,  9, 14, 27, 33, 17, 20, 18,
        3, 30, 35, 34,  2, 23, 25,  7])

In [34]:
batch = np.array_split(rand_data, np.ceil(N/BATCH_SIZE))
batch

[array([25,  7, 24, 19, 36, 28]),
 array([13,  5, 29, 32, 12, 39]),
 array([37, 15, 31,  6,  0, 16]),
 array([38, 21,  8, 11, 22, 10]),
 array([ 4,  1, 26,  9, 14, 27]),
 array([33, 17, 20, 18,  3, 30]),
 array([35, 34,  2, 23, 25,  7])]