# Lession 14 - Minibatches and Epochs

In [35]:
import numpy as np
np.random.seed(0)

In [36]:
BATCH_SIZE = 6
EPOCHS = 2
N = 40

Generate data

In [24]:
data = np.arange(N)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Randomize the data

In [25]:
rand_data = np.random.permutation(data)
rand_data

array([32,  5, 33, 28,  7, 37, 39, 12, 21, 13, 25, 23, 15, 29, 31, 36,  6,
       38,  0, 16, 19,  2, 24,  8, 11, 22, 10,  4,  1, 26,  9, 14, 27, 17,
       20, 18,  3, 30, 35, 34])

Copy data from beginning to end so each set has same amount of data.

In [26]:
rand_data = np.append(rand_data, rand_data[range(int(np.ceil(N/BATCH_SIZE)*BATCH_SIZE-N))])
rand_data

array([32,  5, 33, 28,  7, 37, 39, 12, 21, 13, 25, 23, 15, 29, 31, 36,  6,
       38,  0, 16, 19,  2, 24,  8, 11, 22, 10,  4,  1, 26,  9, 14, 27, 17,
       20, 18,  3, 30, 35, 34, 32,  5])

In [27]:
batch = np.array_split(rand_data, np.ceil(N/BATCH_SIZE))
batch

[array([32,  5, 33, 28,  7, 37]),
 array([39, 12, 21, 13, 25, 23]),
 array([15, 29, 31, 36,  6, 38]),
 array([ 0, 16, 19,  2, 24,  8]),
 array([11, 22, 10,  4,  1, 26]),
 array([ 9, 14, 27, 17, 20, 18]),
 array([ 3, 30, 35, 34, 32,  5])]